# Generated by Django 2.0.5 on 2018-05-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20180521_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(default=1, on_delete='CASCADE', related_name='resources', to='management.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete='CASCADE', related_name='comments', to='management.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.ForeignKey(on_delete='CASCADE', related_name='projects', to='management.Product'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete='CASCADE', related_name='tasks', to='management.Project'),
        ),
    ]
