# Generated by Django 2.0.5 on 2018-05-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180521_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
