# Generated by Django 2.0.5 on 2018-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_resource_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
